--1
UPDATE PACIENTE P SET p.PESO = 8.5
WHERE p.ID_PACIENTE = 1

SELECT * FROM PACIENTE p 

--2
UPDATE MEDICAMENTOS M SET m.ESTOQUE = 50
WHERE m.ID_MEDICAMENTO = 3

SELECT * FROM MEDICAMENTOS m 

--3
UPDATE TUTOR t SET t.DATA_NASCIMENTO = '2001/05/15'
WHERE t.ID_TUTOR = 2

SELECT * FROM TUTOR t 

--4
UPDATE AGENDAMENTO a SET a.MOTIVO = 'Dor de barriga severa'
WHERE a.ID_AGENDAMENTO = 5

SELECT * FROM AGENDAMENTO a 

--5
UPDATE MEDICAMENTOS m SET m.DESCRICAO =  'Anti-inflamatório para articulações'
WHERE m.ID_MEDICAMENTO = 6

SELECT * FROM MEDICAMENTOS m 

--6
UPDATE TUTOR t SET t.NOME = 'Maria Oliveira'
WHERE t.ID_TUTOR = 3

SELECT * FROM TUTOR t 

--7
UPDATE MEDICAMENTOS m SET m.DESCRICAO =  'Aplicar no olho afetado a cada 4 horas'
WHERE m.ID_MEDICAMENTO = 2

SELECT * FROM MEDICAMENTOS m 

--8
UPDATE TUTOR t SET t.ENDERECO = 'Rua dos Girassóis, 123'
WHERE t.ID_TUTOR = 4

SELECT * FROM TUTOR t 

--9
DELETE FROM AGENDAMENTO a
WHERE a.id_agendamento = 7

SELECT * FROM AGENDAMENTO a 

--10
DELETE FROM MEDICAMENTOS m
WHERE m.id_medicamento = 8

SELECT * FROM MEDICAMENTOS m 

--11
DELETE FROM RECEITA r 
  WHERE r.ID_AGENDAMENTO in (SELECT a.ID_AGENDAMENTO 
                              FROM AGENDAMENTO a 
  							 WHERE a.ID_PACIENTE in (SELECT p.ID_PACIENTE 
  						   							 FROM PACIENTE p
 						                            WHERE p.ID_TUTOR = 5));
 
 DELETE FROM AGENDAMENTO a 
  WHERE a.ID_PACIENTE in (SELECT p.ID_PACIENTE 
  						   FROM PACIENTE p
 						  WHERE p.ID_TUTOR = 5);

DELETE FROM paciente p
 WHERE p.ID_TUTOR = 5;

SELECT * FROM RECEITA r 

--12
DELETE FROM RECEITA
WHERE ID_AGENDAMENTO IS NULL

SELECT * FROM RECEITA r 

--13
DELETE FROM TUTOR t
WHERE t.data_nascimento < '1987-01-01'

SELECT * FROM TUTOR t 

--14
DELETE FROM ITENSRECEITA
WHERE ID_RECEITA BETWEEN 7 AND 9

SELECT * FROM ITENSRECEITA i

/* OUTRA ATIVIDADE */
  
/* ATIV 1 */
SELECT SUM(ESTOQUE) AS total_estoque FROM MEDICAMENTOS;

SELECT * FROM MEDICAMENTOS m 

/* ATIV 2*/


/* ATIV 3*/
SELECT MIN(ESTOQUE) AS total_estoque FROM MEDICAMENTOS;

SELECT * FROM MEDICAMENTOS m 

/* ATIV 4*/
SELECT MAX(PESO) AS maior_peso FROM PACIENTE;

SELECT * FROM PACIENTE p 

/* ATIV 5*/
SELECT COUNT(*) AS total_tutores FROM TUTOR;

SELECT * FROM TUTOR t 

/* ATIV 6*/


/* ATIV 7*/
SELECT r.ID_RECEITA, SUM(i.TOTAL_ITEM) AS total_valor
	FROM RECEITA r
	JOIN ITENSRECEITA i ON r.ID_RECEITA = i.ID_RECEITA
	GROUP BY r.ID_RECEITA
	HAVING total_valor > 100;

/* ATIVIDADE LEFT/INNER*/

/* ATIV 1*/
SELECT P.*, T.NOME , T.ENDERECO , T.TELEFONE
FROM PACIENTE p 
LEFT JOIN TUTOR t ON T.ID_TUTOR = P.ID_TUTOR 

/* ATIV 2*/
SELECT P.*, T.*
FROM PACIENTE P
INNER JOIN TUTOR T ON P.ID_TUTOR = T.ID_TUTOR;


/* ATIV 3*/
SELECT T.*, P.NOME , P.ESPECIE , P.RACA
FROM TUTOR t 
INNER JOIN PACIENTE p ON p.ID_PACIENTE = T.ID_TUTOR 

/* ATIV 4*/
SELECT T.*, P.*
FROM TUTOR t 
LEFT JOIN PACIENTE p ON p.ID_PACIENTE = T.ID_TUTOR 


/* ATIV 5*/
SELECT M.*, R.DATA_EMISSAO , I.QUANTIDADE 
FROM MEDICAMENTOS M
LEFT JOIN ITENSRECEITA I ON M.ID_MEDICAMENTO = I.ID_MEDICAMENTO
LEFT JOIN RECEITA R ON I.ID_RECEITA = R.ID_RECEITA;


/* ATIV 6*/
SELECT M.*, R.DATA_EMISSAO , I.QUANTIDADE , I.DOSAGEM
FROM MEDICAMENTOS M
INNER JOIN ITENSRECEITA I ON M.ID_MEDICAMENTO = I.ID_MEDICAMENTO
INNER JOIN RECEITA R ON I.ID_RECEITA = R.ID_RECEITA;

/* ATIV 7*/
SELECT r.DATA_EMISSAO  , i.QUANTIDADE , i.DOSAGEM , p.NOME , p.ESPECIE 
FROM RECEITA r 
LEFT JOIN AGENDAMENTO a ON a.ID_AGENDAMENTO = r.ID_AGENDAMENTO 
LEFT JOIN PACIENTE p ON p.ID_PACIENTE = a.ID_PACIENTE 
LEFT JOIN ITENSRECEITA i ON r.ID_RECEITA = r.ID_RECEITA 

/* ATIV 8*/
SELECT r.DATA_EMISSAO, i.QUANTIDADE, i.DOSAGEM, p.NOME, p.ESPECIE 
FROM RECEITA r 
INNER JOIN AGENDAMENTO a ON a.ID_AGENDAMENTO = r.ID_AGENDAMENTO 
INNER JOIN PACIENTE p ON p.ID_PACIENTE = a.ID_PACIENTE 
INNER JOIN ITENSRECEITA i ON r.ID_RECEITA = i.ID_RECEITA;


/* ATIV 9*/
SELECT R.*, M.NOME , i.DOSAGEM 
FROM RECEITA R
INNER JOIN ITENSRECEITA I ON R.ID_RECEITA = I.ID_RECEITA
INNER JOIN MEDICAMENTOS M ON I.ID_MEDICAMENTO = M.ID_MEDICAMENTO;


/* ATIV 10*/
SELECT R.*, M.* , i.*
FROM RECEITA R
INNER JOIN ITENSRECEITA I ON R.ID_RECEITA = I.ID_RECEITA
INNER JOIN MEDICAMENTOS M ON I.ID_MEDICAMENTO = M.ID_MEDICAMENTO;




